apiVersion: v1
kind: Service
metadata:
  name: dollar-forecast-service
spec:
  selector:
    app: dollar-forecast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
